name: CI / CD
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install echarts
      - run: cd front; npm install; cd ..
      - run: cd front; npm run build; cd ..
      - run: npm install
      - run: npx playwright install --with-deps
      - run: npm run test-ASB


  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: 'sos2324-jul-asb'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - run: npm install echarts
      - run: cd front; npm install; cd ..
      - run: cd front; npm run build; cd ..

      - name : 'Deploy'
        run: gcloud app deploy


